### ISSUE TITLE
Failed to run v2544 using xoa-core

### ISSUE THREAD

**Issue by leonardhyu** [xenanetworks/open-automation-test-suites#10]
### Description:
When trying to run RFC-2544 “Back-to-Back tests” via automation, below error is seen

```
plugin2544.utils.exceptions.FrameDurationRequire: back_to_back Test requires Frames Duration Type.
RFC-2544[b1117e12-6bdf-4829-8a40-79dffac1e409] back_to_back Test requires Frames Duration Type.
/usr/lib/python3.8/asyncio/events.py:81: RuntimeWarning: coroutine 'MainController.list_testers' was never awaited
  self._context.run(self._callback, *self._args)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback -after completion of script run, getting this warning error:
/usr/lib/python3.8/asyncio/events.py:81: RuntimeWarning: coroutine 'MainController.list_testers' was never awaited
  self._context.run(self._callback, *self._args)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

### User environment:
Python version: Python 3.8.10
xoa_converter version: 1.0.3
xoa_core version: 1.0.5
xoa_driver version: 1.0.14
 
plugin2544 and plugin2889 downloaded from https://github.com/XenaNetworks/open-automation-test-suites    

### Config file:

[rfc-2544-ethipv4-thruput-1.v2544.zip](https://github.com/xenanetworks/open-automation-test-suites/files/10457572/rfc-2544-ethipv4-thruput-1.v2544.zip)

**Comment by RonDingDing** [comment]
The error tells where it went wrong, for back_to_back test, only frame duration is allowed. For other tests, only time duration is allowed.

**Comment by RonDingDing** [comment]
https://github.com/xenanetworks/open-automation-test-suites/commit/fa55dd7e70ec7112b5a6a0e4193a4a6705d4d553

**Comment by leonardhyu** [comment]
@RonDingDing so it means in the v2544 config file, the user should use frame duration instead of time duration for b2b test, correct?

**Comment by MaureenChan** [comment]
@leonardhyu Yes, b2b only support frame duration.

**Comment by leonardhyu** [comment]
This can be closed i think. I'll make a note in our user doc, and update the customer with this. Thanks
