### ISSUE TITLE
L2 Single direction flow 

### ISSUE THREAD

**Issue by RonDingDing** [xenanetworks/open-automation-test-suites#4]
Question:
If you send the traffic with only L2(Ethernet), and your topology is "all ports connected to a switch", there is no way for the tx ports to get to know where to send to. So the tester will broadcast to all ports in the network.

Solution:
According to Zohn, asking all the ports to send their mac address before the test will be an idea. (L2 learning)

**Comment by leonardhyu** [comment]
This is what we have already implemented. This is called L2 learning where all ports (strictly speaking all RX ports) send some packets to the switch so the switch can construct its MAC table. I believe 2544 has already had this done, hasn't it?

**Comment by RonDingDing** [comment]
Still the server can't get a correct mac in the app.

**Comment by leonardhyu** [comment]
Not sure if I understand "still the server can't get a correct MAC in the app". To train a L2 DUT (switch) prior to the test with the L2 learning frames, the tester won't get any MAC address from the DUT. Instead what the tester does is simply sending some frames to the DUT to let the DUT learn what MAC addresses are present on its ports, so when the switch needs to forward a frame to a MAC address, it knows where to forward.
